stages:
  - install
  - test

install:
  stage: install
  script:
    - chmod +x tw-install.sh
    - ./tw-install.sh

test:
  stage: test
  script:
    - chmod +x install-bats-libs.sh
    - ./install-bats-libs.sh
    - chmod +x test.sh
    - ./test.sh
